### ISSUE TITLE
where was layernorm placed in downsample layer?

### ISSUE THREAD

**Issue by lucidrains** [lucidrains/uniformer-pytorch#1]
<img width="570" alt="Screen Shot 2021-11-15 at 5 22 00 PM" src="https://user-images.githubusercontent.com/108653/141878550-524d01c5-ed46-4cb6-90ba-a7f94e93074f.png">

paper said an additional layernorm was placed in downsampling layer, but was it placed before or after?

**Comment by Andy1621** [comment]
Thanks for your attention. LN is paced after downsampling.
Our code is available at [UniFormer](https://github.com/Sense-X/UniFormer).

**Comment by lucidrains** [comment]
@Andy1621 i see! thank you https://github.com/lucidrains/uniformer-pytorch/commit/756c4edb7ab0947dc202c145f7c95571848e0594
